version: "3"
services:
  api:
    build: ./api
    container_name: api
    ports:
      - 3000:3000
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./api:/app
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails dev:cache && bundle exec rails s -p 3000 -b '0.0.0.0'"
  front:
    build: ./front
    container_name: front
    ports:
      - 3001:3000
    volumes:
      - ./front:/app
  postgresql:
    image: postgres:15.3
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp_development
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - 6379:6379
